### ISSUE TITLE
Request new config parm announce_rate_limiting

### ISSUE THREAD

**Issue by joseph-reynolds** [deksai/pam_abl#4]
This is a request to enhance pam_abl with a new configuration parameter: announce_rate_limiting.
When used, pam_abl uses return code PAM_RATE_LIMITING when pam_abl chooses to block an authentication request (instead of PAM_AUTH_ERR).

I need this behavior so I can tell my clients that their authentication attempt did not go through because the service is rate limiting authentication attempts and they can try again later.  I am in a controlled environment (like a private network) where there are friendly-fire brute-force attacks that can trigger rate limiting, and I want my clients to be able to distinguish between that situation and actually having entered the wrong password.

See my request to add the PAM_RATE_LIMITING error code here: https://github.com/linux-pam/linux-pam/issues/216

**Comment by deksai** [comment]
@joseph-reynolds After taking a brief look at your links, I have a few questions since my head is not into the problem you are solving as much as you have been.  From the look of it, it appears this request is more than just including a configuration option for a different error code, but also necessarily includes implementing the entire sliding window calculation on attempts, which would bring with it many more configuration options.  For instance, you were thinking to rate limit all attempts while counting only failures.  You also ignore the origin and account name.  I can imagine someone wanting to change both of these behaviours, and perhaps rate limit IPs or only an account which seems to be targeted.  With the database of attempts, which could even be centralised, it would be easy to detect activity focused on certain accounts only.  

So my first question is whether my notion that the scope of your request is quite a bit bigger than it first appears is correct, and that it is asking to implement more than a configuration option.

My second questions is how would you imagine something like this could work for you if the PAM community does not agree to add the extra error code?  Pam-abl could simply `_PAM_RETURN_VALUES + 1` as you have done, but then this is meaningless outside of the module.  The error code could possibly be a configuration option, and compile time options could even adjust documentation about available errors, but I'm not positive this is a good approach.  What are your thoughts?

**Comment by joseph-reynolds** [comment]
Second question first.  I expect the Linux PAM community to resist adding new return codes.  I hope they will consider adding the PAM_RATE_LIMITING code if they can see:
- a popular authentication module (pam_abl) that demonstrates a need for a new code, plus
- an active project (https://github.com/openbmc/openbmc) using pam_abl (planned use) with plans to use the new code, together with the development and testing capabilities to get it done.

The scary part for me is that I cannot find guidelines or best practices for when my web service can safely issue HTTP status 429 (too many requests) (aka rate limiting) without giving too must information to attackers.  I will continue pecking at various security communities to try to get such guidelines.

**Comment by joseph-reynolds** [comment]
Onto your first question.  I would be happy to abandon my [experimental rate-limiting attempt](https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/31841) and I am not tied to it.  Specifically, I believe its configuration items (MaxEvents until panic mode, and the PeriodInSeconds timeout) can be dropped, and I can use existing pam_abl configuration options.  Also, I would like to be sensitive to origin and account name, but did not add them to my primitive prototype, and believe pam_abl would give me what I need.

Specifically, I do not know the scope of this request.  My initial formulation (_use return code PAM_RATE_LIMITING instead of PAM_AUTH_ERR_) represents the main idea.  The change I need may be as simple as an option to change the return code.  I don't understand pam_abl well enough to say.

To clarify, my project wants to use pam_abl as-is.  I  understand we would have some work to make that happen, and would agree to the development and testing effort.  Additionally, I would like to be able to articulate rate-limiting vs genuine auth-failure, and get that into my project's web server.  I guess I'd have to handle my project's serial console login and SSH login vectors.  <-- I hope that helps.

**Comment by deksai** [comment]
As mentioned before, there is no way I can see to articulate between rate limiting and blocking based on too many failures without some real rate tracking within the module.   I am toying with some code to introduce rate limiting in addition to blocking.  This can be done even without the extra error code, although to find out why failures were happening you would need to investigate via the cli tools or configure a command to communicate this via a message bus or send some kind of notification.  The error code returned to PAM would be the standard failure, but the new response could be enabled either by its definition within PAM should that ever happen, or possibly by a flag when compiling.

My time for this, however, only comes in dribs and drabs, so if you can afford to wait, great.  If not, I am open to answering questions if you would like to submit a patch.

**Comment by deksai** [comment]
Hi @joseph-reynolds I apologise, but finding a solid block of time with the appropriate mental space to work on this has been much harder than I imagined.  I apologise for making you wait as long as you have to hear back from me.  Unfortunately, and although it gives me pain to do it, out of fairness to everyone I need to officially cut the project loose.  I'll close this issue for now unless / until  someone else would like to work on it.
